# Generated by Django 3.1.2 on 2020-10-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Usuario')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('password', models.CharField(max_length=100, verbose_name='Senha')),
            ],
        ),
    ]
